# Generated by Django 6.0.2 on 2026-03-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0005_alter_equipment_description_alter_equipment_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='Available', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='static/uploadImages'),
        ),
    ]
