# Generated by Django 6.0.2 on 2026-03-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0007_equipment_totalearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('rent', models.IntegerField()),
                ('owner_address', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='categories',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='totalEarning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
