# Generated by Django 6.0.2 on 2026-03-24 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0008_orders_alter_categories_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='owner_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
