# Generated by Django 6.0.2 on 2026-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.TextField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('name', models.TextField(max_length=50)),
                ('rent', models.IntegerField()),
                ('condition', models.TextField(max_length=50)),
                ('year', models.TextField(max_length=50)),
                ('brand', models.TextField(max_length=50)),
                ('Description', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
