# Generated by Django 6.0.2 on 2026-03-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0003_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriapp.categories'),
        ),
    ]
