# Generated by Django 6.0.2 on 2026-03-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0004_alter_equipment_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='equipment/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
