# Generated by Django 6.0.2 on 2026-03-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0006_equipment_status_alter_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='totalEarning',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
