# Generated by Django 6.0.2 on 2026-03-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0009_orders_owner_remarks_orders_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='address',
            field=models.CharField(default='nagar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
