# Generated by Django 6.0.2 on 2026-03-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0010_user_detail_address_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
