# Generated by Django 6.0.2 on 2026-03-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0011_user_detail_latitude_user_detail_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
