# Generated by Django 6.0 on 2026-05-23 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0012_alter_user_detail_address_alter_user_detail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('canceled', 'Canceled'), ('extend_requested', 'Extension Requested'), ('reduce_requested', 'Early Return Requested')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RentalAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('extend', 'Extend Days'), ('reduce', 'Early Return')], max_length=10)),
                ('new_checkout_date', models.DateField()),
                ('extra_days', models.IntegerField(default=0)),
                ('extra_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('customer_note', models.TextField(blank=True)),
                ('owner_remarks', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='agriapp.orders')),
            ],
        ),
    ]
